version: '3.9'

services:
  flask-api:
    container_name: flask-api
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app           # For your app source code
      - ./data:/app/data         # ✅ Ensures the CSV is visible to the container
    depends_on:
      - my-mongo

  my-mongo:
    image: mongo:latest
    container_name: my-mongo
    ports:
      - "27017:27017"






