services:
  - type: web
    name: cs6440-flu-dashboard
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile
    dockerContext: .
    startCommand: "python app.py"
    healthCheckPath: /

    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000





