services:
  - type: web
    name: cs6440-flu-dashboard
    env: docker
    plan: free
    region: oregon
    dockerfilePath: Dockerfile         # ✅ Was backend/Dockerfile
    dockerContext: .                   # ✅ We're using the root now
    startCommand: "python app.py"
    healthCheckPath: /

    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_USER
        value: fsrinehart
      - key: MONGO_PASS
        value: 1Banana!



