services:
  - type: web
    name: cs6440-flu-dashboard
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    buildCommand: ""
    startCommand: "python app.py"
    healthCheckPath: /

    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_RUN_PORT
        value: 5000

